# -*- coding: utf-8 -*-
"""AI August 13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1spZwwQWvxgY9QR4E4bnkgygNQnG5wADL
"""

import pandas as pd
df=pd.read_csv('/content/Iris.csv')
df

df["Species"].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3},inplace=True)
df

x=df.iloc[:,1:5]
x

y=df.iloc[:,5:]
y

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8)

y

x

import keras #library for neural network
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import numpy as np # linear algebra
import keras

#Neural network module
from keras.models import Sequential
from keras.layers import Dense,Activation,Dropout

model=keras.Sequential()
model.add(Dense(64,input_dim=4,activation='relu'))
model.add(Dense(64,input_dim=4,activation='relu'))
model.add(Dense(64,activation='softmax'))
model.compile(optimizer='adam',loss="sparse_categorical_crossentropy",metrics=['accuracy'])

model.fit(xtrain,ytrain,batch_size=20,epochs=100)

model.evaluate(xtest,ytest)

ans=model.predict(xtest)
ans



#NLP

import spacy
task=spacy.load("en_core_web_sm")

msg=task("I am going to learn python and will find a job in META and earn 1 million dollar")

for i in msg:
  print(i,i.pos_,spacy.explain(i.pos_)) #parts of speech detection

for i in msg.ents:
  print(i.text,i.label_,spacy.explain(i.label_)) #parts of speech detection

#Sentiment Analysis

from textblob import TextBlob
review1="This phone is very budget friendly and working fine"
review2="This phone is very expensive and it has failed to deliver the features"
ans1=TextBlob(review1)
ans2=TextBlob(review2)

print(ans1.sentiment)
print(ans2.sentiment)

